Hw04 auth
RonnieBk/goit-node-hw pull request #3
Opened 2024-02-21 22:48 UTC by RonnieBk

2024-02-22 19:43 UTC, KamilMr requested changes
Razem z autoryzacją trzeba się upewnić że tylko osoba która jest twórcą danego kontaktu może go edytować. I to we wszystkich ścieżkach które obsługują kontakty musisz dodać obsługę tego kontaktu tylko przez autoryzowanego użytkownika. Czyli są dwa poziomy autoryzacji. Pierwszy poziom autoryzacji umożliwia dostęp do ścieżki a drugi poziom autoryzacji umożliwia edycję rekordów w bazie danych. Ten drugi poziom autoryzacji uzyskujemy poprzez klucz owner.

2024-02-22 19:43 UTC, KamilMr commented on middlewares/auth.js
> +      }
```suggestion
        req.user = user;
        next();
```
Tego else nie potrzebujesz bo masz return na gorze i ono zatrzyma wykonanie.

2024-02-22 19:43 UTC, KamilMr commented on middlewares/auth.js
> +          message: "Not authorized",
Warto napisać różne wiadomości do tego pliku jeżeli chodzi o błąd, bo wtedy podczas debugowania będziemy mogli łatwo znaleźć miejsce które powoduje ten błąd.

2024-02-22 19:43 UTC, KamilMr commented on service/controllers/contactsController.js
>      const contacts = await Contact.find();
```suggestion
    const contacts = await Contact.find({owner});
```
Razem z autoryzacją trzeba się upewnić że tylko osoba która jest twórcą danego kontaktu może go edytować. I to we wszystkich ścieżkach które obsługują kontakty musisz dodać obsługę tego kontaktu tylko przez autoryzowanego użytkownika. Czyli są dwa poziomy autoryzacji. Pierwszy poziom autoryzacji umożliwia dostęp do ścieżki a drugi poziom autoryzacji umożliwia edycję rekordów w bazie danych. Ten drugi poziom autoryzacji uzyskujemy poprzez klucz owner.

2024-02-25 08:10 UTC, KamilMr approved these changes
Kilka komentarzy a zadanie zrobione poprawnie. 
Powodzenia w kolejnych :)

2024-02-25 08:10 UTC, KamilMr commented on service/controllers/contactsController.js
>      const contactToDelete = await Contact.findByIdAndDelete({ _id: contactId });
```suggestion
    const contactToDelete = await Contact.findByIdAndDelete({ _id: contactId });
```
Powinnaś jeszcze sprawdzić czy kontakt należy do owner

2024-02-25 08:10 UTC, KamilMr commented on service/controllers/contactsController.js
> +    const contactToUpdate = await Contact.findOne({ _id: contactId });
Mozesz poszukac po dwóch filtrach w tym samym momencie. :)

2024-02-25 11:16 UTC, RonnieBk commented on service/controllers/contactsController.js
>      const contactToDelete = await Contact.findByIdAndDelete({ _id: contactId });
Przeciez jest dalej sprawdzenie owner?

2024-02-25 12:03 UTC, RonnieBk commented
Wszystko zamienilam

2024-02-25 12:04 UTC, merged