Hw05 avatars
RonnieBk/goit-node-hw pull request #4
Opened 2024-02-25 21:35 UTC by RonnieBk

Próbowałam też zrobić dodatkowe zadanie, ale coś mi nie przechodzi axios, ciągle wydaje taki błąd "AxiosError: Request failed with status code 500"
Może podpowiesz mi co jest nie tak?

2024-02-26 20:36 UTC, KamilMr requested changes
Hej
Upewnij się że serwer Ci działa, bo ja nie mogłem go uruchomić. To najpierw zanim będziesz testować axios. :) Dopiero wtedy spróboj zrobić prosty test i może uzyj supertest, tego co było na zajęciach z Maćkiem? 

Staraj się uzywać jednego sposbu, jak uzywasz async await to zostań przy tej metodzie bez uzywania then catch. Bo będzie jasne dla mnie, że rozumiesz uzycie await a też dobrze jest mieć ten sam styl. 

ps. Request failed with status code 500" wskazuje, że serwer zwrócił odpowiedź HTTP 500 Internal Server Error. To zazwyczaj oznacza problem po stronie serwera, a nie z twoim żądaniem Axios.
Testuj Endpointy Ręcznie: Spróbuj uderzyć w endpointy /signup i /login ręcznie, uzywajac postmana. To może pomóc ustalić, czy problem leży w konfiguracji testu, czy w samym serwerze.

Ponadto w axios uzywasz app ale z bazą danych łaczysz się w server. Musisz uzyc server.js :)

2024-02-26 20:36 UTC, KamilMr commented on middlewares/validateUser.js
> +const { requiredUserSchema } = require("../service/schemas/userSchema");
Czy to na pewno działa?

2024-02-26 20:36 UTC, KamilMr commented on service/controllers/userController.js
> +    });
Może użyj jednego sposbu? czyli try catch z await ale bez then żeby gdyby był błąd to go przechwycić.

2024-02-26 20:36 UTC, KamilMr commented on service/controllers/userController.js
> +    next(err);
Tu też musisz dać return next bo inaczej nie przerwi operacji

2024-02-26 20:36 UTC, KamilMr commented on service/controllers/userController.js
> +    return res.status(200).json({
Czy status 200 nie jest domyślną odpowiedzią jak jest ok?

2024-02-27 11:38 UTC, RonnieBk commented on middlewares/validateUser.js
> +const { requiredUserSchema } = require("../service/schemas/userSchema");
zmienilam nazwe zeby bylo w jednym stylu

2024-02-27 21:40 UTC, RonnieBk commented
Nie do konca rozumiem jak ten server mozna wyexportowac z server.js zeby pozniej go podlaczyc w login.test..?
a tak niby dziala

2024-02-28 16:29 UTC, KamilMr approved these changes
Hej, 
zadanie zatwierdzam i powodzenia w dalszej części. :)

2024-03-01 17:50 UTC, merged